# Generated by Django 2.0.5 on 2018-06-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_child_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='duration_in_minutes',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeding',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
